#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "$HOME/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#vmware-user

DROPBOXD=$HOME/.dropbox-dist/dropboxd
if [ -x $DROPBOXD ]; then
  $DROPBOXD &
fi
  
#xdaliclock -24 -noseconds -geometry 100x50 -fn BUILTIN0 -transparent &
#gnome-terminal &
if which urxvt >/dev/null 2>&1; then
  urxvt &
else
  xterm &
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

#exec fluxbox -rc $DOTDIR/fluxbox/init
exec fluxbox -rc $HOME/.fluxbox/init --log $HOME/fluxbox.log
